name: Plot Curves
on:
  push:
    branches:
      - main
jobs:
  plot_curves:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib
    - name: Run the plot_curves script
      run: python main.py